"""
Management command to seed 10 users and 10 Q&A rows.
Usage: python manage.py seed_data
"""

from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from qa.models import UserProfile, Question

USERS = [
    ("alice_em", "alice@example.com"),
    ("bob_tech", "bob@example.com"),
    ("carol_eng", "carol@example.com"),
    ("david_rv", "david@example.com"),
    ("eva_power", "eva@example.com"),
    ("frank_ac", "frank@example.com"),
    ("grace_dc", "grace@example.com"),
    ("henry_tf", "henry@example.com"),
    ("iris_em", "iris@example.com"),
    ("jack_eng", "jack@example.com"),
]

QA_DATA = [
    ("How does a three-phase induction motor work?",
     "A three-phase induction motor works on electromagnetic induction. "
     "Three-phase AC supply creates a rotating magnetic field in the stator. "
     "This field induces current in the rotor, producing torque and rotation."),

    ("What is back EMF in a DC motor?",
     "Back EMF is the voltage generated by the motor opposing the supply voltage. "
     "It increases with speed and limits current draw automatically."),

    ("Explain transformer core losses.",
     "Core losses include hysteresis loss and eddy current loss. "
     "Hysteresis is from repeated magnetization. Eddy currents are reduced by laminations."),

    ("What is synchronous speed?",
     "Synchronous speed = 120 x frequency / poles. "
     "For a 4-pole 50Hz motor: 1500 RPM. Induction motors run slightly below this."),

    ("Difference between motor and generator?",
     "A motor converts electrical energy to mechanical energy. "
     "A generator converts mechanical energy to electrical energy."),

    ("How does a transformer work?",
     "A transformer uses mutual induction. AC in primary creates changing flux. "
     "This induces voltage in secondary. Ratio V1/V2 = N1/N2."),

    ("What causes motor overheating?",
     "Overloading, single phasing, blocked ventilation, frequent starts, "
     "high ambient temperature, and bearing failure all cause overheating."),

    ("What is motor efficiency?",
     "Efficiency = output power / input power x 100. "
     "Losses include copper loss, core loss, and friction loss."),

    ("What is slip in an induction motor?",
     "Slip = (synchronous speed - rotor speed) / synchronous speed x 100. "
     "Typically 2-8% at full load."),

    ("What is a universal motor?",
     "A universal motor runs on both AC and DC. "
     "Used in vacuum cleaners and drills. Can reach very high speeds."),
]


class Command(BaseCommand):
    """Seeds 10 users and 10 Q&A rows into the database."""

    help = 'Seed database with 10 users and 10 Q&A rows'

    def handle(self, *args, **options):
        self.stdout.write('Seeding users...')
        created_users = []

        for username, email in USERS:
            if not User.objects.filter(username=username).exists():
                user = User.objects.create_user(
                    username=username,
                    email=email,
                    password='Test@1234'
                )
                UserProfile.objects.create(
                    user=user,
                    bio='Electrical engineering enthusiast',
                    location='India'
                )
                self.stdout.write(f'  Created: {username}')
            else:
                user = User.objects.get(username=username)
                self.stdout.write(f'  Exists: {username}')
            created_users.append(user)

        self.stdout.write('Seeding Q&A...')
        for i, (question, answer) in enumerate(QA_DATA):
            user = created_users[i % len(created_users)]
            if not Question.objects.filter(question=question).exists():
                Question.objects.create(
                    user=user,
                    question=question,
                    answer=answer
                )
                self.stdout.write(f'  Q&A #{i + 1} created')

        self.stdout.write(self.style.SUCCESS(
            '\nDone! 10 users and 10 Q&A rows seeded.'
            '\nAll passwords: Test@1234'
        ))